version: '3.9'

services:
  db:
    image: postgres:latest
    restart: always
    container_name: postgres_db
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=Abc@1234
      - POSTGRES_DB=bookstore
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    image: client
    container_name: client
    ports:
      - '3000:3000'
    env_file:
      - .env
    depends_on:
      - server
    networks:
      - app-network

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    image: server
    container_name: server
    ports:
      - '8080:8080'
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
